/*
 * Test data strategy for demo.Demo.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2019-05-21 23:36 +0800.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package demo.Demo_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import demo.PackageStrategy_int;
/**
 * Test data strategy for demo.Demo. Provides
 * class-scope test values for type int.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2019-05-21 23:36 +0800
 */
public /*@ nullable_by_default */ class ClassStrategy_int 
  extends PackageStrategy_int {
  /**
   * @return class-scope values for type int.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add class-scope int values or generators here */ });
  }
}
