/*
 * Test data strategy for package demo.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2019-05-22 20:27 +0800.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 package demo;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.DoubleStrategy;

/**
 * Test data strategy for package demo. Provides
 * package-scope test values for type double.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2019-05-22 20:27 +0800
 */
public /*@ nullable_by_default */ class PackageStrategy_double 
  extends DoubleStrategy {
  /**
   * @return package-scope values for type double.
   */
  public RepeatedAccessIterator<?> packageValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add package-scope double values or generators here */ });
  }
}
